### ISSUE TITLE
Transfer repo to Organization: das labor

### ISSUE THREAD

**Issue by pintman** [pintman/workadv_das-labor#9]
Transfer this repo to another organization [das labor](https://github.com/das-labor).

- [x] Become Member of orga
- [x] Be able to create repos in orga
- [x] Update destination of https://virtuallab.das-labor.org
- [x] Change all places containing references to the old repo location - e.g. README.md
- [x] Update remotes in cloned repos.
- [x] Update link in [wiki](https://wiki.das-labor.org/w/Projekt/Virtuelles_Labor), and [here](https://wiki.das-labor.org/w/Location_not_included_2020/Workadventure/basement)

**Comment by Mythozz** [comment]
@fridtjof Please redirect https://virtuallab.das-labor.org to https://play.workadventu.re/_/global/das-labor.github.io/workadv_das-labor/main.json

**Comment by fridtjof** [comment]
Done, closing
